name: 'Open GitHub issue'
description: 'Opens a new GitHub issue in a repository.'
author: 'Vitor'

# Define your inputs here.
inputs:
  token:
    description: 'GitHub token'
    required: true
  title:
    description: 'Issue title'
    required: true
  body:
    description: 'Issue body'
  assignees:
    description: 'Issue Assignees'

# Define your outputs here.
outputs:
  issue: # id of output
    description: 'The issue object as JSON string'

runs:
  using: node20
  main: dist/index.js
